### ISSUE TITLE
Cython support

### ISSUE THREAD

**Issue by SebastianSemper** [spadarian/docblock-python#19]
This is an awesome extension!

It would be really nice, if Cython would be supported, where even more information can be automatically casted into the docstring, since sometimes statically typed function definitions are used.

But as a starting point it would be really helpful, if at least Cython would be allowed by extending the accepted starting keywords with 'cdef' and 'cpdef'.

**Comment by spadarian** [comment]
The syntax of the typing in Cython ("int a") is different from Python ("a: int"), so just adding `cdef` and `cpdef` to the starting keywords wouldn't help much I think.

To fix this issue is necessary to:
1. Modify [`format_lines`](https://github.com/spadarian/docblock-python/blob/59cbdf128c771692cbf0f6a838a301560f61ac11/lib/docblock-python.js#L59) to parse the parameters differently when the starting keyword is `cdef` or `cpdef`.
2. Add the new starting keywords.
3. Extract the type of the returned value (between cdef/cpdef and the name of the function).

An extra task is to add support for things like `except?`, `except*' and probably other things of which I don't know.

I think it is worth implementing this, so I will add it to my todo list. I will also tag this as a "good first issue". If anyone wants to help, let me know so we don't work in the same thing.

**Comment by spadarian** [comment]
@SebastianSemper 
Let me know if that is enough. I have no idea how to document things like "except" or if it even necessary. Let me know if you need me to fix or add something.

**Comment by SebastianSemper** [comment]
@spadarian: Thanks for the nice update! For me on atom 1.32.2, docblock-python version 0.11 and electron 2.0.12 the plugin does not work anymore at all. It always throws me an error with "Nothing to do.Try selecting a line where you define a function or class." 

Should I open an issue? What other info do you need?

**Comment by spadarian** [comment]
Can you post an example of your function?
Are you using Windows?

Travis used electron 2.0.9 but I doubt that is the problem.

José Padarian C.
✉ spadarian@gmail.com
-------------------------------------------------------
Sydney Institute of Agriculture
THE UNIVERSITY OF SYDNEY
Suite 105, Biomedical Building, 1 Central Avenue Australian Technology
Park, Eveleigh, NSW 2015, Australia

**Comment by SebastianSemper** [comment]
I tried

`
def WARNING(string):

    print("\033[91mWARNING:\033[0m %s" % (string))
`

on Manjaro Linux.

**Comment by spadarian** [comment]
So even in a "normal" (no Cython) function...

Just to be sure, your cursor is in the `def WARNING(string):` line, right?

**Comment by spadarian** [comment]
Create a new issue and let's move the conversation there.
No idea how to reproduce the problem but maybe someone else has an idea.
